#!/bin/sh

set -e

[ -f /etc/default/grafinsight-server ] && . /etc/default/grafinsight-server

IS_UPGRADE=false


case "$1" in
	configure)
	[ -z "$GRAFINSIGHT_USER" ] && GRAFINSIGHT_USER="grafinsight"
	[ -z "$GRAFINSIGHT_GROUP" ] && GRAFINSIGHT_GROUP="grafinsight"
	if ! getent group "$GRAFINSIGHT_GROUP" > /dev/null 2>&1 ; then
	    addgroup --system "$GRAFINSIGHT_GROUP" --quiet
	fi
	if ! id $GRAFINSIGHT_USER > /dev/null 2>&1 ; then
	    adduser --system --home /usr/share/grafinsight --no-create-home \
		--ingroup "$GRAFINSIGHT_GROUP" --disabled-password --shell /bin/false \
		"$GRAFINSIGHT_USER"
	fi

	# Set user permissions on /var/log/grafinsight, /var/lib/grafinsight
	mkdir -p /var/log/grafinsight /var/lib/grafinsight
	chown -R $GRAFINSIGHT_USER:$GRAFINSIGHT_GROUP /var/log/grafinsight /var/lib/grafinsight
	chmod 755 /var/log/grafinsight /var/lib/grafinsight

  # copy user config files
  if [ ! -f $CONF_FILE ]; then
    cp /usr/share/grafinsight/conf/sample.ini $CONF_FILE
    cp /usr/share/grafinsight/conf/ldap.toml /etc/grafinsight/ldap.toml
  fi

  if [ ! -d $PROVISIONING_CFG_DIR ]; then
    mkdir -p $PROVISIONING_CFG_DIR/dashboards $PROVISIONING_CFG_DIR/datasources
    cp /usr/share/grafinsight/conf/provisioning/dashboards/sample.yaml $PROVISIONING_CFG_DIR/dashboards/sample.yaml
    cp /usr/share/grafinsight/conf/provisioning/datasources/sample.yaml $PROVISIONING_CFG_DIR/datasources/sample.yaml
  fi

  if [ ! -d $PROVISIONING_CFG_DIR/notifiers ]; then
    mkdir -p $PROVISIONING_CFG_DIR/notifiers
    cp /usr/share/grafinsight/conf/provisioning/notifiers/sample.yaml $PROVISIONING_CFG_DIR/notifiers/sample.yaml
  fi

  if [ ! -d $PROVISIONING_CFG_DIR/plugins ]; then
    mkdir -p $PROVISIONING_CFG_DIR/plugins
    cp /usr/share/grafinsight/conf/provisioning/plugins/sample.yaml $PROVISIONING_CFG_DIR/plugins/sample.yaml
  fi

	# configuration files should not be modifiable by grafinsight user, as this can be a security issue
	chown -Rh root:$GRAFINSIGHT_GROUP /etc/grafinsight/*
	chmod 755 /etc/grafinsight
	find /etc/grafinsight -type f -exec chmod 640 {} ';'
	find /etc/grafinsight -type d -exec chmod 755 {} ';'

  # If $1=configure and $2 is set, this is an upgrade
  if [ "$2" != "" ]; then
    IS_UPGRADE=true
  fi

  if [ "x$IS_UPGRADE" != "xtrue" ]; then
    if command -v systemctl >/dev/null; then
      echo "### NOT starting on installation, please execute the following statements to configure grafinsight to start automatically using systemd"
      echo " sudo /bin/systemctl daemon-reload"
      echo " sudo /bin/systemctl enable grafinsight-server"
      echo "### You can start grafinsight-server by executing"
      echo " sudo /bin/systemctl start grafinsight-server"
    elif command -v update-rc.d >/dev/null; then
      echo "### NOT starting grafinsight-server by default on bootup, please execute"
      echo " sudo update-rc.d grafinsight-server defaults 95 10"
      echo "### In order to start grafinsight-server, execute"
      echo " sudo service grafinsight-server start"
    fi
  elif [ "$RESTART_ON_UPGRADE" = "true" ]; then

    echo -n "Restarting grafinsight-server service..."

    if command -v systemctl >/dev/null; then
      systemctl daemon-reload
      systemctl restart grafinsight-server || true
    elif [ -x /etc/init.d/grafinsight-server ]; then
      if command -v invoke-rc.d >/dev/null; then
        invoke-rc.d grafinsight-server restart || true
      else
        /etc/init.d/grafinsight-server restart || true
      fi
    fi
    echo " OK"

	fi
	;;
esac
