{
 "title": "GrafInsight metrics",
 "description": "Metrics about GrafInsight",
 "tags": [
  "grafinsight",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Active instances",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "up{job=\"grafinsight\"}"
    }
   ]
  },
  {
   "title": "Dashboard count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "grafinsight_stat_totals_dashboard"
    }
   ]
  },
  {
   "title": "User count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "grafinsight_stat_total_users" }
   ]
  },
  {
   "title": "Playlist count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "grafinsight_stat_total_playlists"
    }
   ]
  },
  {
   "title": "GrafInsight version",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "topk(1, grafinsight_info or grafinsight_build_info)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "http status codes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (statuscode) (irate(http_request_total{job='grafinsight'}[5m]))",
     "legendFormat": "{{statuscode}}",
     "target": "dev.grafinsight.cb-office.alerting.active_alerts"
    }
   ]
  },
  {
   "title": "Requests by routing group",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(grafinsight_api_response_status_total[5m]))",
     "legendFormat": "api"
    },
    {
     "expr": "sum(irate(grafinsight_proxy_response_status_total[5m]))",
     "legendFormat": "proxy"
    },
    {
     "expr": "sum(irate(grafinsight_page_response_status_total[5m]))",
     "legendFormat": "web"
    }
   ]
  },
  {
   "title": "Most used handlers",
   "type": "table",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 5 },
   "targets": [
    {
     "expr": "sort(topk(8, sum by (handler) (http_request_total{job=\"grafinsight\"})))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "GrafInsight active alerts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(grafinsight_alerting_active_alerts[1m])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Prometheus alerts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": " sum (ALERTS)", "legendFormat": "firing alerts" }
   ]
  },
  {
   "title": "GrafInsight performance",
   "type": "graph",
   "description": "Aggregated over all GrafInsight nodes.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_goroutines{job=\"grafinsight\"})",
     "legendFormat": "go routines",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "expr": "sum(process_resident_memory_bytes{job=\"grafinsight\"})",
     "legendFormat": "memory usage"
    }
   ]
  }
 ]
}