#! /usr/bin/env bash

# Wrapper for the grafinsight-cli binary
# This file serves as a wrapper for the grafinsight-cli binary. It ensures we set
# the system-wide GrafInsight configuration that was bundled with the package as we
# use the binary.

DEFAULT=/etc/default/grafinsight

GRAFINSIGHT_HOME=/usr/share/grafinsight
CONF_DIR=/etc/grafinsight
DATA_DIR=/var/lib/grafinsight
PLUGINS_DIR=/var/lib/grafinsight/plugins
LOG_DIR=/var/log/grafinsight

CONF_FILE=$CONF_DIR/grafinsight.ini
PROVISIONING_CFG_DIR=$CONF_DIR/provisioning

EXECUTABLE=$GRAFINSIGHT_HOME/bin/grafinsight-cli

if [ ! -x $EXECUTABLE ]; then
 echo "Program not installed or not executable"
 exit 5
fi

# overwrite settings from default file
if [ -f "$DEFAULT" ]; then
  . "$DEFAULT"
fi

OPTS="--homepath=${GRAFINSIGHT_HOME} \
      --config=${CONF_FILE} \
      --pluginsDir=${PLUGINS_DIR} \
      --configOverrides='cfg:default.paths.provisioning=$PROVISIONING_CFG_DIR \
                        cfg:default.paths.data=${DATA_DIR} \
                        cfg:default.paths.logs=${LOG_DIR} \
                        cfg:default.paths.plugins=${PLUGINS_DIR}'"

eval $EXECUTABLE "$OPTS" "$@"
