{
 "title": "Cloud Storage Monitoring",
 "tags": [
  "Storage",
  "Cloud Monitoring",
  "GCP"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "stackdriver" },
   {
    "name": "project",
    "label": "Project",
    "query": {}
   },
   {
    "name": "alignmentPeriod",
    "label": "Alignment Period",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Cloud Storage Monitoring",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard has 6 charts for the related [Cloud Storage metrics](https://cloud.google.com/monitoring/api/metrics_gcp#gcp-storage), including `Total object count`, `Total bytes`, `Bucket object count`, `Bucket total bytes`, `Bucket - Received/Sent Bytes`, and `Bucket - Request count`."
   }
  },
  {
   "title": "Total object count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "gcs_bucket"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "storage.googleapis.com/storage/object_count",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Total bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "gcs_bucket"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "storage.googleapis.com/storage/total_bytes",
      "projectName": "$project",
      "unit": "By",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Bucket object count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "gcs_bucket"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "storage.googleapis.com/storage/object_count",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Bucket total bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "gcs_bucket"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "storage.googleapis.com/storage/total_bytes",
      "projectName": "$project",
      "unit": "By",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Bucket - Received bytes, Sent bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "gcs_bucket"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "storage.googleapis.com/network/received_bytes_count",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "gcs_bucket"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "storage.googleapis.com/network/sent_bytes_count",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Bucket - Request count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "gcs_bucket"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "storage.googleapis.com/api/request_count",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  }
 ]
}