{
 "title": "MicroService Monitoring",
 "tags": [
  "Microservices",
  "Cloud Monitoring",
  "GCP"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "stackdriver" },
   {
    "name": "project",
    "label": "Project",
    "query": {}
   },
   {
    "name": "alignmentPeriod",
    "label": "Alignment Period",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "MicroService Monitoring",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard has 8 charts to display the metrics for the microservices in our [demo application](https://github.com/GoogleCloudPlatform/microservices-demo). The metrics include request count, response latencies, and request/response bytes."
   }
  },
  {
   "title": "Server Request Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "k8s_container"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "istio.io/service/server/request_count",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Server Response Latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_PERCENTILE_99",
      "filters": [
       "resource.type",
       "=",
       "k8s_container"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "istio.io/service/server/response_latencies",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    }
   ]
  },
  {
   "title": "Server Response Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_PERCENTILE_99",
      "filters": [
       "resource.type",
       "=",
       "k8s_container"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "istio.io/service/server/response_bytes",
      "projectName": "$project",
      "unit": "By",
      "valueType": "DISTRIBUTION"
     }
    }
   ]
  },
  {
   "title": "Server Request Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_PERCENTILE_99",
      "filters": [
       "resource.type",
       "=",
       "k8s_container"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "istio.io/service/server/request_bytes",
      "projectName": "$project",
      "unit": "By",
      "valueType": "DISTRIBUTION"
     }
    }
   ]
  },
  {
   "title": "Client Roundtrip Latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_PERCENTILE_99",
      "filters": [
       "resource.type",
       "=",
       "k8s_pod"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "istio.io/service/client/roundtrip_latencies",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    }
   ]
  },
  {
   "title": "Client Request Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "k8s_pod"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "istio.io/service/client/request_count",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Client Response Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_PERCENTILE_99",
      "filters": [
       "resource.type",
       "=",
       "k8s_pod"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "istio.io/service/client/response_bytes",
      "projectName": "$project",
      "unit": "By",
      "valueType": "DISTRIBUTION"
     }
    }
   ]
  },
  {
   "title": "Client Request Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_PERCENTILE_99",
      "filters": [
       "resource.type",
       "=",
       "k8s_pod"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "istio.io/service/client/request_bytes",
      "projectName": "$project",
      "unit": "By",
      "valueType": "DISTRIBUTION"
     }
    }
   ]
  }
 ]
}