#!/bin/sh

set -e

echo "POSTTRANS: Running script"

[ -f /etc/sysconfig/grafinsight-server ] && . /etc/sysconfig/grafinsight-server

# copy config files if missing
if [ ! -f /etc/grafinsight/grafinsight.ini ]; then
  echo "POSTTRANS: Config file not found"

  if [ -f /etc/grafinsight/grafinsight.ini.rpmsave ]; then
    echo "POSTTRANS: /etc/grafinsight/grafinsight.ini.rpmsave config file found."
    mv /etc/grafinsight/grafinsight.ini.rpmsave /etc/grafinsight/grafinsight.ini
    echo "POSTTRANS: /etc/grafinsight/grafinsight.ini restored"

    if [ -f /etc/grafinsight/ldap.toml.rpmsave ]; then
      echo "POSTTRANS: /etc/grafinsight/ldap.toml.rpmsave found"
      mv /etc/grafinsight/ldap.toml.rpmsave /etc/grafinsight/ldap.toml
      echo "POSTTRANS: /etc/grafinsight/ldap.toml restored"
    fi

    echo "POSTTRANS: Restoring config file permissions"
    chown -Rh root:$GRAFINSIGHT_GROUP /etc/grafinsight/*
    chmod 755 /etc/grafinsight
    find /etc/grafinsight -type f -exec chmod 640 {} ';'
    find /etc/grafinsight -type d -exec chmod 755 {} ';'
  fi
fi


