#!/bin/sh

set -e

[ -f /etc/sysconfig/grafinsight-server ] && . /etc/sysconfig/grafinsight-server

startGrafInsight() {
  if [ -x /bin/systemctl ] ; then
    /bin/systemctl daemon-reload
		/bin/systemctl start grafinsight-server.service
	elif [ -x /etc/init.d/grafinsight-server ] ; then
		/etc/init.d/grafinsight-server start
	elif [ -x /etc/rc.d/init.d/grafinsight-server ] ; then
		/etc/rc.d/init.d/grafinsight-server start
	fi
}

stopGrafInsight() {
	if [ -x /bin/systemctl ] ; then
		/bin/systemctl stop grafinsight-server.service > /dev/null 2>&1 || :
	elif [ -x /etc/init.d/grafinsight-service ] ; then
		/etc/init.d/grafinsight-service stop
	elif [ -x /etc/rc.d/init.d/grafinsight-service ] ; then
		/etc/rc.d/init.d/grafinsight-service stop
	fi
}


# Initial installation: $1 == 1
# Upgrade: $1 == 2, and configured to restart on upgrade
if [ $1 -eq 1 ] ; then
	[ -z "$GRAFINSIGHT_USER" ] && GRAFINSIGHT_USER="grafinsight"
	[ -z "$GRAFINSIGHT_GROUP" ] && GRAFINSIGHT_GROUP="grafinsight"
	if ! getent group "$GRAFINSIGHT_GROUP" > /dev/null 2>&1 ; then
    groupadd -r "$GRAFINSIGHT_GROUP"
	fi
	if ! getent passwd "$GRAFINSIGHT_USER" > /dev/null 2>&1 ; then
    useradd -r -g grafinsight -d /usr/share/grafinsight -s /sbin/nologin \
    -c "grafinsight user" grafinsight
	fi

  # copy user config files
  if [ ! -f $CONF_FILE ]; then
    cp /usr/share/grafinsight/conf/sample.ini $CONF_FILE
    cp /usr/share/grafinsight/conf/ldap.toml /etc/grafinsight/ldap.toml
  fi

  if [ ! -d $PROVISIONING_CFG_DIR ]; then
    mkdir -p $PROVISIONING_CFG_DIR/dashboards $PROVISIONING_CFG_DIR/datasources
    cp /usr/share/grafinsight/conf/provisioning/dashboards/sample.yaml $PROVISIONING_CFG_DIR/dashboards/sample.yaml
    cp /usr/share/grafinsight/conf/provisioning/datasources/sample.yaml $PROVISIONING_CFG_DIR/datasources/sample.yaml
  fi

  if [ ! -d $PROVISIONING_CFG_DIR/notifiers ]; then
    mkdir -p $PROVISIONING_CFG_DIR/notifiers
    cp /usr/share/grafinsight/conf/provisioning/notifiers/sample.yaml $PROVISIONING_CFG_DIR/notifiers/sample.yaml
  fi

  if [ ! -d $PROVISIONING_CFG_DIR/plugins ]; then
    mkdir -p $PROVISIONING_CFG_DIR/plugins
    cp /usr/share/grafinsight/conf/provisioning/plugins/sample.yaml $PROVISIONING_CFG_DIR/plugins/sample.yaml
  fi

 	# Set user permissions on /var/log/grafinsight, /var/lib/grafinsight
	mkdir -p /var/log/grafinsight /var/lib/grafinsight
	chown -R $GRAFINSIGHT_USER:$GRAFINSIGHT_GROUP /var/log/grafinsight /var/lib/grafinsight
	chmod 755 /var/log/grafinsight /var/lib/grafinsight

	# configuration files should not be modifiable by grafinsight user, as this can be a security issue
	chown -Rh root:$GRAFINSIGHT_GROUP /etc/grafinsight/*
	chmod 755 /etc/grafinsight
	find /etc/grafinsight -type f -exec chmod 640 {} ';'
	find /etc/grafinsight -type d -exec chmod 755 {} ';'

  if [ -x /bin/systemctl ] ; then
    echo "### NOT starting on installation, please execute the following statements to configure grafinsight to start automatically using systemd"
    echo " sudo /bin/systemctl daemon-reload"
    echo " sudo /bin/systemctl enable grafinsight-server.service"
    echo "### You can start grafinsight-server by executing"
    echo " sudo /bin/systemctl start grafinsight-server.service"
  elif [ -x /sbin/chkconfig ] ; then
    echo "### NOT starting grafinsight-server by default on bootup, please execute"
    echo " sudo /sbin/chkconfig --add grafinsight-server"
    echo "### In order to start grafinsight-server, execute"
    echo " sudo service grafinsight-server start"
  fi
elif [ $1 -ge 2 ] ; then
  if [ "$RESTART_ON_UPGRADE" == "true" ]; then
    stopGrafInsight
    startGrafInsight
  fi
fi
