FROM ubuntu:20.04

ARG REPO_CONFIG=grafinsight.list.oss
ARG PACKAGE=grafinsight

RUN apt update && \
    apt install -y curl                \
                   apt-transport-https \
                   ca-certificates     \
                   gnupg               && \
    curl https://packages.grafinsight.com/gpg.key | apt-key add -

COPY "./$REPO_CONFIG" /etc/apt/sources.list.d/grafinsight.list
RUN apt update && \
    apt install -y $PACKAGE
